plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id "co.uzzu.dotenv.gradle" version "2.0.0"

    id "me.modmuss50.mod-publish-plugin" version "2.0.0-beta.2"
}

version = project.mod_version
group = project.maven_group

repositories {
    maven {
        name = "Nucleoid"
        url = 'https://maven.nucleoid.xyz/releases'
        metadataSources {
            artifact()
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation include("eu.pb4:placeholder-api:${project.placeholder_api_version}")
}

processResources {
    inputs.properties([
            version: project.version,
            loader_version: project.loader_version,
            minecraft_depends: project.minecraft_depends,
    ])

    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand inputs.properties
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}


publishMods {
    file = jar.archiveFile

    type = STABLE

    version = project.mod_version
    displayName = 'ItemRename ' + project.mod_version
    changelog = file("CHANGELOG.md").text

    modLoaders.add("fabric")

    curseforge {
        projectId = "711029"
        projectSlug = "itemrename"
        accessToken = env.CURSEFORGE_TOKEN.orNull()
        minecraftVersions.addAll(project.curseforge_versions.split(","))
        client = true
        server = true
        requires("fabric-api")
        requires("text-placeholder-api")
    }
    modrinth {
        projectId = "i5cjb3PQ"
        accessToken = env.MODRINTH_TOKEN.orNull()
        minecraftVersionList(project.modrinth_versions)
        requires("P7dR8mSH") // Fabric API
        requires("eXts2L7r") // Text placeholder api
    }
}
