# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=1.0.3+26.1.2
maven_group=gay.nyako
archives_base_name=itemrename
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.149.1+26.1.2
placeholder_api_version=3.0.0+26.1

functional_versions=26.1.2